version: '3.5'

services:
  app:
    build:
      context: docker/app
    user: ${CURRENT_UID:-1000:1000}
    working_dir: /var/www
    ports:
      - 8000:8000
    depends_on:
      - chrome
    volumes:
      - ./:/var/www

  chrome:
    image: selenium/standalone-chrome:3.141.59-europium
    user: ${CURRENT_UID:-1000:1000}
    volumes:
      - /dev/shm:/dev/shm
      - ./tmp:/home/seluser/Downloads
    ports:
      - "5999:5999"

